FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore AutonomusCRM.Workers/AutonomusCRM.Workers.csproj
RUN dotnet publish AutonomusCRM.Workers/AutonomusCRM.Workers.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AutonomusCRM.Workers.dll"]
